FROM node:10.10.0-jessie
ENV LANG="C.UTF-8"
WORKDIR /root

RUN apt-get update && apt-get install -y cron && yarn global add dmhy-subscribe
CMD echo 'start dmhy-subscribe' && cron && tail -f /var/log/cron.log
