name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  run-test:
    name: 🧪 Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        # aka actions/checkout@v7.0.1

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86
        # aka pnpm/action-setup@v6.0.10

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        # aka actions/setup-node@v7.0.0
        with:
          node-version: 24
          package-manager-cache: false

      - run: pnpm install --frozen-lockfile

      - run: pnpm run check
